# Generated by Django 3.2.7 on 2021-09-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clases', models.CharField(max_length=250, verbose_name='буква класса')),
                ('number', models.IntegerField(default=1, verbose_name='номер класса')),
                ('teacher', models.CharField(max_length=255, verbose_name='классная руководительница')),
            ],
            options={
                'verbose_name_plural': 'класс',
            },
        ),
    ]
