# Generated by Django 3.2.7 on 2021-09-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О.')),
                ('plase', models.CharField(max_length=100, verbose_name='Место проживание')),
                ('phone', models.IntegerField(unique=True, verbose_name='номер телефона')),
                ('image', models.ImageField(blank=True, upload_to='image')),
            ],
            options={
                'verbose_name_plural': 'Учителя',
            },
        ),
    ]
